### ISSUE TITLE
filter buttons not working anymore in citation library

### ISSUE THREAD

**Issue by gt150** [ResetNetwork/recoding-tech#101]
@jheretic @rudietuesdays @harumhelmy The filter buttons in the citation library do not seem to be working anymore
 
<img width="1240" alt="Screen Shot 2022-03-08 at 1 45 05 PM" src="https://user-images.githubusercontent.com/9727494/157304700-957aa0ce-dc9d-4e6d-9b55-05b84d52ac31.png">

**Comment by harumhelmy** [comment]
Hey @gt150! Sorry about this confusion -- we still haven't been able to merge these fixes from the test site to the production site because some AWS problems we were running into. @jheretic and I have been working on a fix though, and we're testing it right now! Fingers crossed we can merge the fixes to production this afternoon.

**Comment by harumhelmy** [comment]
@gt150 YAYYY THE FIXES ARE NOW ON THE PRODUCTION SITE!!!!!! https://recoding.tech/search check it out!

**Comment by harumhelmy** [comment]
Also! We are aware that the citation listings in the Search page does not yet reflect the wireframes -- I'm working on those fixes and will push to the test site soon!

**Comment by gt150** [comment]
> @gt150 YAYYY THE FIXES ARE NOW ON THE PRODUCTION SITE!!!!!! https://recoding.tech/search check it out!

Looks like it's working.
