### ISSUE TITLE
standardize styling for "headlines & highlights" / further reading sections

### ISSUE THREAD

**Issue by katiewilson21** [ResetNetwork/recoding-tech#103]
* Remove the author from display on the homepage (creates a strange hyphen when no author is present) 
* Use the text styling from the homepage (ie smaller, italics text for the date)

**Comment by gt150** [comment]
@harumhelmy Thanks. I appreciate the logic fix, but I wonder if it would just be simpler to only list the title and publication outlet. I don't think it's that important to have the author listed, especially since we have so many citations with multiple authors. Related to the publication listing, I'm noticing that items categorized as reports in Zotero do not list the publication outlet when they show up on recoding.tech. For example:
<img width="1098" alt="Screen Shot 2022-03-23 at 4 21 54 PM" src="https://user-images.githubusercontent.com/9727494/159789011-ba9088d3-98e2-4d1f-bb34-6632e393a0f4.png">
I think this might be a matter of not including the "institution" field as part of the options for the publication outlet. The citation database is already pulling in that info from Zotero, but it's currently not being used to generate the text when it shows up the headlines/highlights.
![Screen Shot 2022-03-23 at 4 26 51 PM](https://user-images.githubusercontent.com/9727494/159789651-6dd44287-ef70-4e36-a7eb-56ca489cb80b.png)

**Comment by harumhelmy** [comment]
hey @gt150 -- the logic fix for ensuring all manner of publication title/place/institution is up on test.recoding.tech, not on recoding.tech, yet. See below an example from the test site. Would you still like me to remove the authors' names? 
![Screen Shot 2022-03-24 at 09 45 26](https://user-images.githubusercontent.com/13320420/159929806-d705ee04-1950-4a42-bb64-b4dab80bd7af.png)

**Comment by gt150** [comment]
@harumhelmy got it. great! Let's go and ahead and remove the author from the display (keep collecting it from zotero and putting it into the cms database though).

**Comment by harumhelmy** [comment]
@gt150 Done! Some items don't have any publication info, FYI! For example, citation ID 8M4VFMU6 and 4BT3CSGA

**Comment by katiewilson21** [comment]
@harumhelmy one more tweak here; can you adjust the spacing so that there is space between the title and author rather than the author and date? so it should look like this: 
<img width="683" alt="image" src="https://user-images.githubusercontent.com/84089903/169614157-84bf7b5b-611d-43ac-9c1e-a5ea2454bb32.png">

and try to remove the line from under the last entry of any headlines and highlights section :)

**Comment by katiewilson21** [comment]
looks great!
