### ISSUE TITLE
Ability for assigned "topics" on "policy actions" to automatically update referenced topic and if topic published, show up on topics page

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#19]

**Comment by rudietuesdays** [comment]
This is a non-trivial lift. A more trivial lift would be to only allow published `topics` to be selected on `policy actions` -- would that suffice (at least in the interim, if not as a solution)?

**Comment by danblah** [comment]
Oh yes, I think so!

So the workflow would be... 
1. Publish a "topic" as a company/country/issue/policy
2. Create "Policy action", see list of published "topics", assign 1 or more
3. Publish "Policy action"
3. Policy action automatically shows up on the "topic" page assigned when creating "Policy action"

????

**Comment by danblah** [comment]
Confirming we want this behaviour per @gt150's answer https://github.com/ResetNetwork/recoding-tech/issues/39

**Comment by harumhelmy** [comment]
This is in progress! Currently, the workflow would be:

1. Set a `topic` as a company/country/issue/policy 
2. Set its `stackbit_model_type` as `page` (so that it's published on the frontend)
3. Click **Publish** on the topic
4. Create a new `Policy action`, on the drop down for `Related topics`, see a list of `topic`s that have been published as a `page`
5. Policy action automatically shows up on the "topic" page assigned when creating "Policy action"

Will ping when pushed to staging @gt150 @danblah @rudietuesdays

**Comment by harumhelmy** [comment]
Ready for testing, pending @jheretic's approval!

**Comment by harumhelmy** [comment]
Ready for testing!

**Comment by gt150** [comment]
@harumhelmy seems to be working!

**Comment by danblah** [comment]
great work, closing!
