### ISSUE TITLE
On each "Type of Topic" page (issue, policy, country, company), show related citations under the "Latest Headlines & Highlights" sidebar

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#23]

**Comment by rudietuesdays** [comment]
Trivial update, can do by early next week

**Comment by danblah** [comment]
Rocking! Let me know when you've got something for me to review!

**Comment by rudietuesdays** [comment]
Pushed to staging!

**Comment by danblah** [comment]
@rudietuesdays, not seeing this. I'm not exactly how I'm supposed to test this.

see this page: https://recoding-tech-v2.netlify.app/policy/antitrust

My assumption is that somewhere in the edit page for it here https://recoding-tech-2d607.sanity.studio/desk/topic;antitrust I should be able to add Citations from this list here https://recoding-tech-2d607.sanity.studio/desk/citation and then they would show up on in a "Latest Headlines & Highlights" box on the antitrust page. 

Is that your understanding?

**Comment by harumhelmy** [comment]
I'm working on this -- should be ready by Monday @danblah

**Comment by harumhelmy** [comment]
Ugh, this turned out to be something less much trivial than we thought fyi @danblah. 

@jheretic -- this is the issue I was talking to you about the other day. For each `citation` document, the script that imports data from Zotero imports each document's tags but didn't/doesn't connect each tag to the corresponding `topic` document on our database, it instead creates a brand new object called topic. Which means Sanity has no idea about this relationship! 

I think a fix to this could be writing a script that batch replaces each existing `citation` document's Topic property (which is made up of its tags on Zotero), into a `topic` document in the db that corresponds to that tag. Does this make sense? The word topic has lost all meaning to me.

**Comment by rudietuesdays** [comment]
@danblah pushed a fix for this!

**Comment by gt150** [comment]
@rudietuesdays it's look like it's only pulling from recoding articles, not citations. For example on the antitrust page it only lists an article I wrote, but none of the citations in the CMS database that are tagged for antitrust. 
![Screen Shot 2022-02-01 at 2 34 30 PM](https://user-images.githubusercontent.com/9727494/152038381-1bd05c57-abe2-4f20-adfa-c6b8939b0e20.png)

**Comment by rudietuesdays** [comment]
Confirming that this is related to #80 ? There's been some confusion around the difference between this and the related reading section if they both contain citations and articles, and right now the fix is that this sidebar section has been removed and the slider (which is working) remains. Let us know if this sounds right.

**Comment by gt150** [comment]
@rudietuesdays just clarify that these are not related. The related reading at the bottom of pages is for recoding. tech articles. And the sidebar "Headlines and highlights" is for the most recent items from the citation database that are tagged with the relevant topic. For example, on the antitrust page we should see 4 to 5 of the most recent items from the citation database that are tagged with topic 'antitrust.' These are supposed to flow in automatically. The design also called for the user to be able to click on "view all" and be taken to the library page with appropriate filter button selected.

**Comment by rudietuesdays** [comment]
@gt150 got it, I've readded the Headlines & Highlights section. Previously we had been told that both sections should be able to accept citations *and* articles, so we've done a bunch of work to make it possible for those sections to accept both of those content types. We can either remove that functionality, or leave it in and it'll be up to your or another editor's discretion as to what to include in either section. Does the latter work, or would it be better if we remove the functionality for both?

**Comment by gt150** [comment]
@rudietuesdays Yeah, I think that was the thinking at some point, but given the evolution of the website I'd like to keep each section focused on the two distinct types of content. You can just leave alone the related reading widget, since I manually add those to each page type and so it doesn't matter than I can select citations in the CMS. However we need to remove the ability of "headline and highlights" to pull from recoding.tech articles. It should only pull from the citations database.

**Comment by harumhelmy** [comment]
I'm closing this -- we're currently tracking the issues brought up here in #76 instead.
