### ISSUE TITLE
About page needs styling / remove duplcate

### ISSUE THREAD

**Issue by katiewilson21** [ResetNetwork/recoding-tech#28]
the "Learn more" link on the homepage and the "about" link in the footer should go to the same single page, which needs styling (per [https://www.figma.com/file/L9szOsvQdhyumMOGEz4VnI/?node-id=44%3A2046](the prototype) ).  MVP= intro text and header. Can add contact form later.

**Comment by rudietuesdays** [comment]
The links can be updated in the CMS, for the homepage it's under Advanced Pages > Home and for the footer it's under Site Configuration > Footer. The styles for the About page are in complete but haven't been uploaded yet due to a build error that we're working on. Let me know if that's enough to close this issue out!

**Comment by katiewilson21** [comment]
Titles need capitalization, too

**Comment by katiewilson21** [comment]
Is the styling updated, @rudietuesdays ?

**Comment by danblah** [comment]
looks good
