### ISSUE TITLE
Dates in Zotero for citations are not copying over to the sanity citation reliably, or i think so

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#43]
How often is this happening?

Here's the citation https://recoding-tech-2d607.sanity.studio/desk/citation;2GJIAUUZ
Here's the zotero (which has the date) https://www.zotero.org/groups/2490364/recoding/search/trump/titleCreatorYear/items/2GJIAUUZ/item-list

**Comment by jheretic** [comment]
Double-checking now, but I believe this is because the import script doesn't overwrite content (to make sure there's no data loss), so if there were edits in Zotero after the import they won't get picked up. This could be resolved by deleting the citation and letting it re-import (which is what I'm checking on now in the development dataset), but perhaps we need more complex import logic to dynamically merge edits that have occurred after the import date without overwriting any sanity-specific data.

**Comment by gt150** [comment]
I think that's likely the case. Unfortunately, it's not really sustainable to manually maintain two ledgers of citations and track specific citation changes. Zotero really does need to be the master list and the citation database should update each citation (both old and new) from that. It's not just a problem with editing dates and fixing errors in the citations, but also if I want to add tags down the road I would need to add them manually in the citation database for existing citations. That would be a real nightmare.

**Comment by danblah** [comment]
Seems to be resolved (dates are the same and copying over). thanks @jheretic. @gt150, lets keep an eye for this in case it comes up again.
