### ISSUE TITLE
Add an analytics tool

### ISSUE THREAD

**Issue by danblah** [ResetNetwork/recoding-tech#92]
https://simpleanalytics.com/

What are other good options?

**Comment by rudietuesdays** [comment]
Netlify offers analytics for an additional $9/month: https://docs.netlify.com/monitor-sites/analytics/

Also I know Cloudflare has a certain amount of analytics -- are you looking for any data in particular?

**Comment by danblah** [comment]
i wanna know what other sites/countries people are coming from (did anyone click the links in ben's newsletter to get here, are austrailans coming here and sad there's no au content), what pages they spend the most time on (how popular specific pages are), what pages they bounce from the most (are there specific design elements that need to change)... most of the things here: https://docs.simpleanalytics.com/data-points

**Comment by danblah** [comment]
We've been using matomo. We could keep using that too but i belive it does require a gdpr consent/

**Comment by yaelrst** [comment]
After talking with Dan about it: either simplyanalytics or matomo are good options, whichever doesn't require a consent pop up. For now because we have Netlify we can keep using that as throneless figures out which one they want to use/what's the best option. Once you do decide and need to sign up for/pay for an account lmk and I can get that set up with you.
